services:
  - type: web
    name: oscaretto-gym-tracker-app
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist/oscaretto-gym-tracker/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html